apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xlice-com-ng
  namespace: certs
  annotations:
    cert-manager.io/cluster-issuer: staging
    kubernetes.io/tls-acme: 'true'
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: xlice-com-ng
  issuerRef:
    name: staging
    kind: ClusterIssuer
  dnsNames:
    - "*.xlice.com.ng"