apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: emart-routes
  namespace: emart-app
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "3"
spec:
  parentRefs:
  - name: cluster-gateway
    namespace: gateway
  hostnames:
  - "emart.xlice.com.ng"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /webapi
    backendRefs:
    - name: webapi-svc
      port: 9000
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: api-svc
      port: 5000
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: client-svc
      port: 4200