apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emongo-statefulset
  namespace: emart-app
  annotations:
    # argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceName: "emongo"
  selector:
    matchLabels:
      app: emongo-pod
  #serviceName: "emongo"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: emongo-pod
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 120
      containers:
      - name: emongo-container
        image: mongo:4
        volumeMounts:
        - name: mongo-vol
          mountPath: /var/mongo-data
        env:
        - name: MONGO_INITDB_DATABASE
          value: epoc
        ports:
        - containerPort: 27017
          name: emongo-port
        readinessProbe:
          tcpSocket:
            port: emongo-port
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: emongo-port
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 10
        startupProbe:
          tcpSocket:
            port: emongo-port
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
      volumes:
      - name: mongo-vol
        persistentVolumeClaim:
          claimName: mongo-pvc
        

---
apiVersion: v1
kind: Service
metadata:
  name: emongo
  namespace: emart-app
spec:
  #clusterIP: None
  selector:
    app: emongo-pod
  ports:
  - protocol: TCP
    port: 27017
    targetPort: emongo-port
