apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cluster-gateway
  namespace: gateway
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  gatewayClassName: cluster-gateway-class
  infrastructure:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz/ready"
      service.beta.kubernetes.io/port_443_health-probe_protocol: "http"
      service.beta.kubernetes.io/port_443_health-probe_port: "15021"
      service.beta.kubernetes.io/port_15021_health-probe_request-path: "/healthz/ready"
  listeners:  # Use GatewayClass defaults for listener definition.
  - name: https
    protocol: HTTPS
    port: 443
    # hostname: argocd.xlice.com.ng
    allowedRoutes:
      namespaces:
        from: All
        # from: Selector
        #   selector:
        #     matchLabels:
        #       name: apps
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: xlice-com-ng
        namespace: certs
