apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: emart-app
  annotations:
    argocd.argoproj.io/hook: Sync  
    argocd.argoproj.io/sync-wave: "0"
spec:
  storageClassName: default # Empty string must be explicitly set otherwise default StorageClass will be set
  # volumeName: mongo-pv
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # selector:
  #   matchLabels:
  #     environment: "dev"